FEAT: Users Signup GET/POST API & Login POST API
hanghae10-w6-team5/backend pull request #27
Opened 2022-12-20 11:01 UTC by crystalyst

Users Signup GET/POST API & Login POST API Added.

Things to note: Given the index route sets the default route for user router as "/users," the APIs below should be modified as follows:

POST /api/signup -> /api/users/signup
GET /api/signup/:id -> /api/users/signup/:id
POST /api/login -> /api/users/login

Uncommitted / incomplete progress that need to be resolved
- User GET API 
- Refresh Token (using an object from the helper class - tokenObject)
- Auth Middleware
- Error-handler Middleware

2022-12-20 12:44 UTC, jn33-dev approved these changes
로그인 api에서, 기존에 토큰 값이 있는지 검증할때, req.token으로 처리하면 되는지만 확인해주시면 될듯 합니다!

2022-12-20 12:44 UTC, jn33-dev commented on src/controllers/users.controller.js
> +            if (req.token) {
req.token으로 해도 req.headers에 있는 token 값이 읽히나요??

2022-12-20 12:44 UTC, jn33-dev commented on src/services/users.service.js
> +        return target_user;
굳이 리턴 필요 없어 보입니다!

2022-12-20 12:44 UTC, jn33-dev commented on src/controllers/users.controller.js
> +                message: "ID Validated"
성공 메세지에 "사용 가능한 id입니다."로 바꿀까요?
한글 자판 안되셔서 영어로 치신 듯..ㅋㅋㅋ

2022-12-20 13:08 UTC, Yoseb-Han approved these changes

2022-12-20 13:24 UTC, joohyang0612 approved these changes

2022-12-21 01:17 UTC, crystalyst commented on src/controllers/users.controller.js
> +            if (req.token) {
Checked - Resolved this issue in the upcoming PR

2022-12-21 01:20 UTC, crystalyst commented on src/services/users.service.js
> +        return target_user;
Checked - Resolved this issue in the upcoming PR

2022-12-21 01:20 UTC, crystalyst commented on src/controllers/users.controller.js
> +                message: "ID Validated"
Yes ;) thank you so much!!

2022-12-21 02:53 UTC, jn33-dev requested changes
몇가지 수정사항 반영해서 다시 푸쉬 부탁드리고, 
의견 남겨달라고 한 커멘트도 있으니 확인하셔서 의견 주시면 감사하겠습니다 :)

2022-12-21 02:53 UTC, jn33-dev commented on src/util/auth-jwtToken.util.js
> +const setCookieExpiration = function (hours) {
저희 쿠키 발행은 하지 않아서 이 함수는 삭제하시면 될것 같습니다.

2022-12-21 02:53 UTC, jn33-dev commented on src/controllers/users.controller.js
> +            if (req.token) {
req.get('authentication')

2022-12-21 02:53 UTC, jn33-dev commented on src/controllers/users.controller.js
> +            return res.cookie("authorization", `Bearer%${token}`).status(200).json({
제승님, 저희 쿠키 사용 안할거라서, res 쿠키로 날리시면 안됩니다ㅋㅋ 
프런트에서 받을 때 에러 난다고 매니저님들이 쿠키로 하지 말고 바디에 토큰 값만 찍어서 보내라고 하더라고요.
쿠키 발행 부분 삭제 부탁드립니다~

2022-12-21 02:53 UTC, jn33-dev commented on src/middlewares/auth-middleware.js
> +    Users.findByPk(userId).then((user) => {
레이어드 아키텍처를 적용했기 때문에, 인증 미들웨어에서 db에 직접 접근하는 것은 부적절해 보입니다.
토큰 payload에 userId 값이 담겨 있으니, userId 값만 res.locals.user (혹은 res.locals.userId)로 보내주시면 좋을것 같습니다.

만약 유저 전체 데이터가 필요한 경우는, 인증미들웨어에서 userId를 Users controller로 전달하고, 레이어들을 통해서 비지니스 로직이 처리되도록 해야 할것 같습니다.

2022-12-21 02:53 UTC, jn33-dev commented on src/middlewares/auth-token-checker.middleware.js
> +        if (req.cookies['authorization']) {
프런트에서 req.headers에 쿠키가 아니라 {authorization: token}의 오브젝트를 보내고 있기 때문에, 이 부분도 수정이 필요합니다.
req.get('authorization') 메소드로 파싱이 가능합니다.

2022-12-21 02:53 UTC, jn33-dev commented on src/middlewares/auth-middleware.js
> +  if (!authToken || authType !== "Bearer") {
로그인 했을 때, 쿠키에 토큰을 담지 않기 때문에, req.headers 값에는 토큰 타입 없이 token 값만 존재합니다.
  
만약에 타입을 포함하고 싶다면, 토큰 발행시 res.body에 담을 때, {authorization: `Bearer ${token}`}과 같이 수정하시면 될것 같습니다.

2022-12-21 02:53 UTC, jn33-dev commented on src/controllers/users.controller.js
> +            const { userId } = res.locals.user;
아래 인증 미들웨어에서 userId 값만 보낼거기 때문에, 이 부분도 구조분해 할당 말고, 그냥 userId에 할당하는 것으로 변경하시면 됩니다.

2022-12-21 02:53 UTC, jn33-dev commented on src/controllers/users.controller.js
> +                throw new InvalidParamsError('알 수 없는 오류가 발생했습니다.', 400);
InvalidParamsError 보다는 AuthenticationError가 어떨까요?
이 경우는, 인증 미들웨어에서 userId를 파싱하면서 뭔가 오류가 있는 경우일텐데, InvalidParamsError로 하면, 뭔가 클라이언트에서 값이 아예 안 왔다고 해석이 될것 같아요.
의견 남겨주세요~

2022-12-21 02:53 UTC, jn33-dev commented on src/routes/users.route.js
>  router.post('/signup', usersController.signUpUser);
회원가입시, 로그인 되어 있는 회원이 다시 회원가입을 시도하는 경우가 발생할 수 있으니까, authTokenChecker를 거쳤다가 와야 할것 같은데, 어떻게 생각하시는지 의견 주세요~

그런데, 이렇게 적용하려면, 애초에 프런트에서 막아야 하나...??? 헷갈리네요ㅋㅋ

2022-12-21 05:00 UTC, crystalyst commented on src/routes/users.route.js
>  router.post('/signup', usersController.signUpUser);
I also thought that FE would handle this - If adding authTokenChecker on signup api makes more sense, I am not against it!

2022-12-21 05:00 UTC, crystalyst commented on src/util/auth-jwtToken.util.js
> +const setCookieExpiration = function (hours) {
Resolved

2022-12-21 05:00 UTC, crystalyst commented on src/controllers/users.controller.js
> +            return res.cookie("authorization", `Bearer%${token}`).status(200).json({
Resolved

2022-12-21 05:00 UTC, crystalyst commented on src/middlewares/auth-middleware.js
> +    Users.findByPk(userId).then((user) => {
Resolved

2022-12-21 06:52 UTC, jn33-dev approved these changes

2022-12-21 06:52 UTC, jn33-dev commented on src/app.js
> +app.get('/', async (req, res) => {
제승님, 여기 코드는 왜 필요한가요??

2022-12-21 06:52 UTC, jn33-dev commented on src/middlewares/auth-middleware.js
> +    throw new AuthenticationError('로그인이 필요한 서비스입니다.', 412);
여기 next(err)로 에러 핸들러로 넘겨주셔야 하는데...;;;
일단 주무시러 가셨으니 제가 머지 후 풀 땡겨서 수정할께요~

2022-12-21 06:52 UTC, merged