Feature/8
hanghae10-w6-team5/backend pull request #29
Opened 2022-12-20 15:28 UTC by Yoseb-Han

게시글 삭제 api 작성
#8

2022-12-20 16:21 UTC, jn33-dev reviewed
요셉님, 커멘트 드린 부분 수정해주시고, 내일 백엔드 다 합치고 나서 레포지토리 부분 수정 진행해주세요~

2022-12-20 16:21 UTC, jn33-dev commented on src/controllers/posts.controller.js
> +            if (!title || !detail || !price || thumbnail) {
thumbnail 값은 없어도 포스팅이 되게 해야 합니다~

2022-12-20 16:21 UTC, jn33-dev commented on src/controllers/posts.controller.js
> +            await this.postsService.findPost(postId);
여기서 findOne 하시면 안되고, postsService 안에서 postId로 검색해서 있다면 삭제하는 로직으로 구현하셔야 합니다~

2022-12-20 16:21 UTC, jn33-dev commented on src/repositories/posts.repository.js
> +        const deletePost = await this.postsModel.destroy({
여기 변수를 선언할 필요 없이, 바로 return으로 하시면 됩니다.
레포지토리 안에 다른 메서드도 다 동일합니다~

2022-12-20 16:21 UTC, jn33-dev commented on src/services/posts.service.js
> +                Comment.map((c) => {
레포지토리에서 getAllComment 하실 때, comments의 updatedAt을 기준으로 sort 해주세요.
sequelize order 메서드 사용하시면 됩니다.

2022-12-20 16:21 UTC, jn33-dev commented on src/services/posts.service.js
> +            throw new ValidationError('게시글을 삭제하였습니다.', 200);
에러메세지 확인해주세요ㅋㅋ
성공메세지를 에러로 뿌리면 어케요ㅋㅋ
deletePost == 0 이면, 삭제가 안됐다는 의미입니다..ㅎㅎㅎㅎㅎ

2022-12-20 16:21 UTC, jn33-dev commented on src/services/posts.service.js
> +        return deletePost;
사실상 return 값으로 넘어가는게 0 또는 1 숫자라서 의미가 없습니다.
return 하지 않으셔도 되고, return 쓰고 싶으시면
return true로 하시면 더 의미가 있을 것 같아요

2022-12-21 00:52 UTC, Yoseb-Han commented on src/controllers/posts.controller.js
> +            if (!title || !detail || !price || thumbnail) {
넵!  feaure/8에 적용했습니다:)

2022-12-21 00:52 UTC, Yoseb-Han commented on src/controllers/posts.controller.js
> +            await this.postsService.findPost(postId);
넵!  feaure/8에 적용했습니다:)

2022-12-21 00:52 UTC, Yoseb-Han commented on src/repositories/posts.repository.js
> +        const deletePost = await this.postsModel.destroy({
넵!  feaure/8에 적용했습니다:)

2022-12-21 00:52 UTC, Yoseb-Han commented on src/services/posts.service.js
> +                Comment.map((c) => {
넵!  feaure/8에 적용했습니다:)

2022-12-21 00:52 UTC, Yoseb-Han commented on src/services/posts.service.js
> +            throw new ValidationError('게시글을 삭제하였습니다.', 200);
넵!  feaure/8에 적용했습니다:)

2022-12-21 00:52 UTC, Yoseb-Han commented on src/services/posts.service.js
> +        return deletePost;
넵!  feaure/8에 적용했습니다:)

2022-12-21 01:51 UTC, jn33-dev requested changes
요셉님, 수정사항이 많네요ㅋㅋㅋ
화이팅..!!

2022-12-21 01:51 UTC, jn33-dev commented on src/controllers/likes.controller.js
> +const { authenticate } = require('passport');
passport 라이브러리가 여기서는 필요 없는것 같은데, 사용하지 않는  상수/변수 선언은 모두 삭제해주세요

2022-12-21 01:51 UTC, jn33-dev commented on src/controllers/likes.controller.js
> +const { ValidationError } = require('sequelize');
ValidationError는 sequelize 모듈에서 가져오시면 안되고, 윗줄에 InvalidParamsErorr 구조분해 할당 옆에 같이 넣어시면 됩니다.
두개가 이름만 같고 다른 클래스랍니다ㅎㅎ

2022-12-21 01:51 UTC, jn33-dev commented on src/controllers/likes.controller.js
> +            const userId = req.get('userId');
이 부분 이제 res.locals.user로 바꾸면 될것 같습니다.

2022-12-21 01:51 UTC, jn33-dev commented on src/controllers/likes.controller.js
> +            if (!postId)
params 값은 url에 포함되는데, 애초에 없으면 api 호출 자체가 안되어서, 이 부분은 삭제하셔도 됩니다~

2022-12-21 01:51 UTC, jn33-dev commented on src/services/likes.services.js
> +        const existLike = await this.likesRepository.createPostLike(
위에서 변경한 메소드 이름으로 변경해주세요.

여기 보고 createPostLike라고 되어 있어서 sequelize create 메소드를 시전하는 줄 알았습니다;;;

2022-12-21 01:51 UTC, jn33-dev commented on src/services/likes.services.js
> +        return existLike;
여기서 return할게 아니라, 위의 if 문 안에서 각각의 상황에 따라 return true / false로 반환하시면 될것 같습니다. 
-> 여기 수정 하시고, controller도 수정해주시면 되겠습니다.

existLike는 좋아요 누르기/취소 후의 existLike가 아니라 createPostLike 메서드 시작할때, 좋아요 확인 여부시에 생성된 existLike라서 코드를 읽을 때 헷갈립니다...;;

2022-12-21 01:51 UTC, jn33-dev commented on src/repositories/likes.repository.js
> +    createPostLike = async (postId, userId) => {
메소드 안에서 실제로 수행하는 기능을 토대로 이름을 지어주세요.
코드 블럭 안에서 like 여부를 조회하기 위해 findOne을 수행 중이니까, checkPostLike라던지 하는 이름으로 바꿔주시면 좋을것 같습니다.

2022-12-21 01:51 UTC, jn33-dev commented on src/controllers/likes.controller.js
> +                throw new InvalidParamsError(
userId가 없다면 AthenticationError를 발생시키는 것이 맞습니다.
다른 메서드에서도 userId를 받는 곳에는 해당 검증 과정을 추가해주세요.

2022-12-21 01:51 UTC, jn33-dev commented on src/controllers/posts.controller.js
> +            const userId = 1;
userId = res.locals.user로 모두 바꿔주세요~

2022-12-21 01:51 UTC, jn33-dev commented on src/repositories/posts.repository.js
>          return comment;
여기도 아래 deletePost와 마찬가지로, comment만 리턴하신다면, 굳이 comment 변수로 선언하지 마시고 바로 return 해주세요.
그리고, 오전 중에 이 부분 Posts 모델에서 inner joint로 코멘트값 가져가는 방식으로 변경하셔야 합니다.

2022-12-21 05:28 UTC, Yoseb-Han commented on src/repositories/posts.repository.js
>          return comment;
넵 수정했습니다:)

2022-12-21 05:29 UTC, Yoseb-Han commented on src/controllers/posts.controller.js
> +            const userId = 1;
넵 수정했습니다:)

2022-12-21 05:29 UTC, Yoseb-Han commented on src/controllers/likes.controller.js
> +                throw new InvalidParamsError(
넵 수정했습니다:)

2022-12-21 05:29 UTC, Yoseb-Han commented on src/repositories/likes.repository.js
> +    createPostLike = async (postId, userId) => {
넵 수정했습니다:)

2022-12-21 05:29 UTC, Yoseb-Han commented on src/services/likes.services.js
> +        return existLike;
넵 수정했습니다:)

2022-12-21 05:29 UTC, Yoseb-Han commented on src/services/likes.services.js
> +        const existLike = await this.likesRepository.createPostLike(
넵 수정했습니다:)

2022-12-21 05:29 UTC, Yoseb-Han commented on src/controllers/likes.controller.js
> +            if (!postId)
넵 수정했습니다:)

2022-12-21 05:29 UTC, Yoseb-Han commented on src/controllers/likes.controller.js
> +            const userId = req.get('userId');
넵 수정했습니다:)

2022-12-21 05:29 UTC, Yoseb-Han commented on src/controllers/likes.controller.js
> +const { ValidationError } = require('sequelize');
넵 수정했습니다:)

2022-12-21 05:29 UTC, Yoseb-Han commented on src/controllers/likes.controller.js
> +const { authenticate } = require('passport');
넵 수정했습니다:)

2022-12-21 06:27 UTC, crystalyst approved these changes

2022-12-21 06:42 UTC, joohyang0612 approved these changes

2022-12-21 06:42 UTC, joohyang0612 commented on src/controllers/posts.controller.js
> +                    40
에러 40  뒤에 숫자 4 하나가 빠진듯합니닷 :)

2022-12-21 06:42 UTC, joohyang0612 commented on src/controllers/posts.controller.js
> +                    40
에러 40  뒤에 숫자 4 하나가 빠진듯합니닷 :)

2022-12-21 07:12 UTC, Yoseb-Han commented on src/controllers/posts.controller.js
> +                    40
오우 확인 감사합니다. 수정했습니다!

2022-12-21 07:12 UTC, Yoseb-Han commented on src/controllers/posts.controller.js
> +                    40
오우 확인 감사합니다. 수정했습니다!

2022-12-21 08:25 UTC, jn33-dev approved these changes
천천히 수정 부탁드립니다.

2022-12-21 08:25 UTC, jn33-dev commented on src/repositories/posts.repository.js
> +        return deletePost;
위에서 리턴하시고 또 리턴하시면..ㅋㅋㅋ 여기 줄 삭제해주세요.
그리고 repository 내에 다른 메서드들도 모두 db 조회한 값을 그대로 반환하고 있으므로, 변수로 선언하지 마시고, 바로 return 때려주세요 ㅋㅋ
혹시 모두 변경하기 귀찮으시면, 변수선언이든, 바로 리턴이던 한가지 스타일로 통일하시면 됩니다.

2022-12-21 08:25 UTC, jn33-dev commented on src/services/likes.services.js
> +} = require('../exception/index.exception');
아래 코드 본문에서 사용하지 않는 것들은 모두 삭제해주세요.

2022-12-21 08:25 UTC, jn33-dev commented on src/services/posts.service.js
> +                id: updatePost.id,
이거 inner joint라서 이렇게 하면 key 값이 없을텐데요? 확인해주세요~

2022-12-21 09:07 UTC, Yoseb-Han commented on src/services/posts.service.js
> +                id: updatePost.id,
수정 완료했습니다:)

2022-12-21 09:25 UTC, merged

2022-12-21 09:26 UTC, Yoseb-Han commented on src/services/likes.services.js
> +} = require('../exception/index.exception');
넵 수정했습니다:)